spring:
  application:
    name: playground
  datasource:
#    url: ${AWS_ENDPOINT}
    url: jdbc:mysql://localhost:3306/umc-7th
#    username: ${AWS_USERNAME} #heehunjung
    username: root
#    password: ${AWS_PASSWORD}
    password: Skyskzz12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
