spring:
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  access:
    secret: "testtesttesthhjhhj"
    expiration: 1800000  # 30분
  refresh:
    secret: "testtesttesthhjhhj"
    expiration: 86400000 # 1일

