application:
  name: playground

spring:
  profiles:
    active: dev
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-version: 1

logging:
  level:
    root: info

oauth:
  google:
    end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes: profile, email
    access-type: online
    token-uri: https://oauth2.googleapis.com/token
    redirect-uri: ${GOOGLE_REDIRECT_URL}
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  kakao:
    token-uri: https://kauth.kakao.com/oauth/token
    redirect-uri: http://localhost:8080/oauth2/kakao
    user-info-uri: https://kapi.kakao.com/v2/user/me
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    api-key: ${KAKAO_API_KEY}
